export { default as HomePage } from './HomePage'
export { default as MainPage } from './MainPage'
export { default as ProcessingPage } from './ProcessingPage'
export { default as FaqPage } from './FAQ'
export { default as ProblemsPage } from './ProblemsPage'